name: matching_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.0.5 <4.0.0'
dependencies:
    flutter_localizations:
        sdk: flutter
    cupertino_icons: ^1.0.2
    flutter_svg: ^2.0.7
    flutter_cupertino_date_picker_fork: ^1.0.7
    filter_list: ^1.0.2
    image_picker: ^0.8.9
    image_cropper: ^5.0.0
    scroll_page_view: ^1.0.2
    carousel_slider: ^4.2.1
    carousel_indicator: ^1.0.6
    modal_bottom_sheet: ^3.0.0-pre
    adaptive_action_sheet: ^2.0.2
    wheel_chooser: ^1.1.2
    app_settings: ^4.2.0
    permission_handler: ^10.3.0
    bloc: ^8.1.2
    flutter_bloc: ^8.1.3
    http: ^1.1.0
    flutter_screenutil: ^5.6.0
    fluttertoast: ^8.1.1
    shared_preferences: ^2.0.17
    flutter_riverpod: 2.0.0-dev.9 #^2.1.1
    freezed_annotation: ^2.2.0
    dio: ^4.0.6
    rxdart: ^0.27.5
    grouped_list: ^5.1.2
    flutter_line_sdk: ^2.3.3
    firebase_core: ^2.15.0
    firebase_auth: ^4.7.2
    provider: 
    cloud_firestore: ^4.8.4
    firebase_messaging: ^14.6.5
    firebase_storage: ^11.2.5
    pay: ^1.1.2
    sign_in_with_apple: ^5.0.0
    intl_phone_field: ^3.2.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: any
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
    generate: true
  # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/images/icons/
        - assets/images/identity/
        - assets/images/community/
        - assets/images/login/
        - assets/images/svg/
        - assets/images/status/
        - assets/images/main/
        - assets/images/users/
        - assets/gpay.json
        - assets/applepay.json
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages